---
application:
  name: "unfurling"
  project: "vuchat"
  organization: "QoveryCommunity"
  storage:
  - name: "vuchat"
    size: "10"
    type: "fast_ssd"
    mount_point: "/mnt/vuchat"
routers:
- name: "main-unfurling"
  routes:
  - application_name: "unfurling"
    paths:
    - "/*"
